= epsilon-runtime-eclipse

image::https://github.com/BlackBeltTechnology/epsilon-runtime-eclipse/actions/workflows/build.yml/badge.svg?branch=develop[link="https://github.com/BlackBeltTechnology/epsilon-runtime-eclipse/actions/workflows/build.yml" float="center"]
It is epsilon compatible version of epsilon-runtime.

It acts as an eclipse plugin with features and sites.

== Modules:

- epsilon-runtime-eclipse - eclipse plugin. It wrapes execution engine.

- feature - Eclipse feature repository - to be able to use for eclipse installation

- site - Eclipse Update Site - all built version compiled as an update site.

== What is Epsilon?

From: https://www.eclipse.org/epsilon/

Epsilon is a family of languages and tools for code generation, model-to-model transformation, 
model validation, comparison, migration and refactoring that work out of the box with EMF, 
UML, Simulink, XML and other types of models.

The currently supported epsilon language dialects are:

 - EOL (Epsilon Object Language)
 - ETL (Epsilon Transformation Language)
 - EVL (Epsilon Validation Language)
 - EGL (Epsilon Generation Language)
 - EGX (Epsilon Generation XML(?))
 - EML (Epsilon Merging Language)
 - ECL (Epsilon Comparison Language)


To understand the epsilon stack recommended to read the free epsilon book: https://www.eclipse.org/epsilon/doc/book/

== Contributing to the project

Everyone is welcome to contribute to epsilon-runtime! As a starter, please read the corresponding link:CONTRIBUTING.adoc[CONTRIBUTING] guide for details!


== License

This project is licensed under the https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt[Eclipse Public License 2.0].
